module.exports = {
	// set your styleguidist configuration here
	title: 'Default Style Guide',
	components: 'src/components/**/**/main.vue',
  ignore:[
    '**/__tests__/**',
    '**/components/alert/**',
    '**/components/aside/**',
    '**/components/autocomplete/**',
    '**/components/avatar/**',
    '**/components/backtop/**',
    '**/components/badge/**',
    '**/components/breadcrumb/**',
    '**/components/breadcrumb-item/**',
    '**/components/button/**',
    '**/components/button-group/**',
    '**/components/calendar/**',
    '**/components/card/**',
    '**/components/carousel/**',
    '**/components/carousel-item/**',
    '**/components/cascader/**',
    '**/components/cascader-panel/**',
    '**/components/checkbox/**',
    '**/components/checkbox-button/**',
    '**/components/checkbox-group/**',
    '**/components/col/**',
    '**/components/collapse/**',
    '**/components/collapse-item/**',
    '**/components/color-picker/**',
    '**/components/container/**',
    '**/components/date-picker/**',
    '**/components/dialog/**',
    '**/components/divider/**',
    '**/components/drawer/**',
    '**/components/dropdown/**',
    '**/components/dropdown-item/**',
    '**/components/dropdown-menu/**',
    '**/components/footer/**',
    '**/components/form/**',
    '**/components/form-item/**',
    '**/components/header/**',
    '**/components/icon/**',
    '**/components/image/**',
    '**/components/input/**',
    '**/components/input-number/**',
    '**/components/link/**',
    '**/components/main/**',
    '**/components/menu/**',
    '**/components/menu-item/**',
    '**/components/menu-item-group/**',
    '**/components/option/**',
    '**/components/option-group/**',
    '**/components/page-header/**',
    '**/components/pagination/**',
    '**/components/popconfirm/**',
    '**/components/popover/**',
    '**/components/progress/**',
    '**/components/radio*/**',
    '**/components/rate/**',
    '**/components/row/**',
    '**/components/scrollbar/**',
    '**/components/select/**',
    '**/components/slider/**',
    '**/components/spinner/**',
    '**/components/step/**',
    '**/components/steps/**',
    '**/components/submenu/**',
    '**/components/switch/**',
    '**/components/tab-pane/**',
    '**/components/table/**',
    '**/components/table-column/**',
    '**/components/tabs/**',
    '**/components/tag/**',
    '**/components/time-picker/**',
    '**/components/time-select/**',
    '**/components/timeline/**',
    '**/components/timeline-item/**',
    '**/components/tooltip/**',
    '**/components/transfer/**',
    '**/components/tree/**',
    '**/components/upload/**',
  ],
	// defaultExample: true,
	sections: [
	  {
	    name: 'Documentation',
	    components: 'src/components/**/main.vue'
	  }
	],
	// webpackConfig: {
	//   // custom config goes here
	// },
	exampleMode: 'expand'
}
