<template>
  <dm-table-list
    :http="http"
    :table-conf="tableConf"
    @selection-change="handleSelectionChange"
    @current-change="handlePageChange"
    @sort-change="sortChange"
  />
</template>
<script>
  import { http } from "../../lib/http";

  export default {
    data(){
      return {
        tableConf:{
          selectableMultiPage:true,
          unixId:'uid',
          pages:{
            size:10
          },
          dataResource:{
            list:[{
              uid:'3344',
              name:'11'
            },{
              uid:'44',
              name:'11'
            }],
            total:2
          },
          thead:[
            {
              type:'selection',
              width:55
            },
            {
              value:'账号ID',
              key:'uid',
              sortable:true
            },
            {
              value:'name',
              key:'name',
              sortable:true
            },
            {
              value:'操作',
              type:'operation'
            }
          ],
          filters:{
            _OPERATION_(h,row,vm){
              return h('div',[
                h('dm-button',{
                  props:{
                    type:'text'
                  },
                  on:{
                    click(){
                      console.log(vm)
                    }
                  }
                },'编辑')
              ])
            }
          },
        },
        http:http
      }
    },
    methods:{
      handleSelectionChange(roe){
        console.log(roe,'roe')
      },
      handlePageChange(pn,rn,page){
        console.log(pn,rn,page)
      },
      sortChange(obj){
        console.log(obj)
      }
    }
  }
</script>
