<template>
  <dm-table-list
    :http="http"
    :table-conf="tableConf"
    @selection-change="handleSelectionChange"
  />
</template>
<script>
  import { http } from "../../lib/http";

  export default {
    data(){
      return {
        tableConf:{
          selectableMultiPage:true,
          unixId:'uid',
          pages:{
            size:10
          },
          dataResource:{
            list:[{
              uid:'3344',
            },{
              uid:'44',
            }],
            total:2
          },
          thead:[
            {
              type:'selection',
              width:55
            },
            {
              value:'账号ID',
              key:'uid'
            },
            {
              value:'操作',
              type:'operate'
            }
          ],
          operateFilter(h,row,vm){
            return h('div',[
              h('dm-button',{
                props:{
                  type:'text'
                },
                on:{
                  click(){
                    console.log(vm)
                  }
                }
              },'编辑')
            ])
          }
        },
        http:http
      }
    },
    methods:{
      handleSelectionChange(roe){
        console.log(roe,'roe')
      }
    }
  }
</script>
